### ISSUE TITLE
permission issues 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/docker-compose-galaxy-annotation#1]
FYI @erasche  . . found when testing here:

https://github.com/TAMU-CPT/galaxy-apollo/issues/2

```
Fatal error: Exit code 1 ()
cp: cannot create directory ‘/apollo-data/6’: Permission denied
INFO:__main__:Determining if add or update required
INFO:__main__:  Adding Organism
INFO:__main__:Updating permissions for <User 19: Bob Jones <admin@galaxy.org>>
```

The default permissions were: `drwxr-xr-x   2 root   root   4096 May 28 16:19 apollo-data`

Did a:

chmod -R 777 /apollo-data

locally and it fixed it.

Not sure if the fix goes here or in the image file directly.

**Comment by hexylena** [comment]
Are you mounting the volume outside of the image at all? If you aren't... https://github.com/erasche/docker-galaxy-annotation/blob/master/Dockerfile#L21 should already be doing that. Hmm.

**Comment by nathandunn** [comment]
I'll retest this morning and see.  Could be left over junk. 

Nathan

**Comment by nathandunn** [comment]
Same issue after torching volumes, images and a fresh clone.   Permissions are the same as above:

```
root@694cd1e8f2e9:/apollo-data# ls -ltrca
total 8
drwxr-xr-x   2 root root 4096 May 31 15:10 .
drwxr-xr-x 112 root root 4096 May 31 15:10 ..
```

I know you're running it in the image . . . do you think maybe you have to run it after the image has been loaded? 

Running the command afterwards works fine:

docker exec -it 694cd1e8f2e9 chmod 777 /apollo-data 

Could this be a separate command?

**Comment by hexylena** [comment]
@nathandunn crap, that's really frustrating.

I'm not sure where we'll run it after launch (without doing something silly like a cron job or another container that just sits there and runs chowns on a loop). I'll think about it a bit more today.

**Comment by nathandunn** [comment]
Everything else seems to work as far as I can tell.   We did fix this issue on master, which is pretty nasty. 

https://github.com/GMOD/Apollo/issues/1077

We'll be issuing an RC1 momentarily for Apollo . . .so it might be a good time to rebuild.

**Comment by nathandunn** [comment]
@erasche Should I retry this (i.e., were you able to create another image with a potential fix?)?

**Comment by hexylena** [comment]
Not yet, other things got in the way. Will ping asap I.can fix
1. jun. 2016 4.31 p.m. skrev "Nathan Dunn" notifications@github.com:

**Comment by nathandunn** [comment]
NP thanks.

**Comment by hexylena** [comment]
Ok, Galaxy image now re-write permissions on /apollo-data every minute. Should be good enough for this...

**Comment by nathandunn** [comment]
Ha ,,. . . okay I'll take a look.  We're trying to do a 2.0.3 release, but we'll see.   If I get REMOTE_USER to work, it can be off of a branch or a post-master release as well.

**Comment by hexylena** [comment]
@nathandunn ok, sounds good!
