### ISSUE TITLE
unable to register a user

### ISSUE THREAD

**Issue by nathandunn** [GMOD/docker-compose-galaxy-annotation#6]
![screen shot 2016-06-13 at 6 54 03 pm](https://cloud.githubusercontent.com/assets/751274/16028853/4f19237c-3198-11e6-91ef-a6d9191988a0.png)

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/galaxy-central/tools/apollo/create_account.py", line 26, in <module>
    if u.username == args.email][0]
IndexError: list index out of range
```

from 

```
python /galaxy-central/tools/apollo/create_account.py $GALAXY_WEBAPOLLO_URL $GALAXY_WEBAPOLLO_USER $GALAXY_WEBAPOLLO_PASSWORD admin@galaxy.org --first "Nathan" --last "Dunn" > /export/galaxy-central/database/files/000/dataset_4.dat
```

Everything in the environment is being set.  Is it using a remote over a local package I wonder?

**Comment by hexylena** [comment]
Aye, something's wrong with the galaxy image installation. I'm not sure
what it is, I'll have to check into that later.
I think something is wrong with the JBrowse package.

I'll try and get it sorted tomorrow.

**Comment by nathandunn** [comment]
Weird .. on the mac I don't get this error, but definitely getting it here:

<img width="1120" alt="screen shot 2016-06-14 at 9 56 01 am" src="https://cloud.githubusercontent.com/assets/751274/16051834/4ed283ee-3216-11e6-9288-2cd269d29856.png">

**Comment by nathandunn** [comment]
So . . . the register error is due to this:

<AXY_WEBAPOLLO_URL $GALAXY_WEBAPOLLO_USER $GALAXY_WEBAPOLLO_PASSWORD admin@galaxy.org --first "Nathan" --last "Dunn"

This is the user that we passed in:

```
admin@galaxy.org
```

This is the user that is loaded in the system:

```
<User 18: Ad min <admin@local.host>>
```

So when we get to this line:

```
user = [u for u in wa.users.loadUsers()
        if u.username == args.email][0]
```

We get a null pointer when trying to get the argument out.   So, whatever you are using for your `apollo-config.groovy` is creating a user "Ad min / admin@local.host" and not returning them.

**Comment by nathandunn** [comment]
still looking . . I understand what is supposed to happen.  FYI, you still need to update to the latest:

```
Exception: Unexpected response from apollo 500: {"error":"Cannot cast object 'false' with class 'java.lang.Boolean' to class 'org.codehaus.groovy.grails.web.json.JSONObject'"}
```

This is an older error suggesting that you are not validated (its rendering instead of returning a boolean).  

It looks like you are trying to update a user even though the user doesn't exist.

**Comment by nathandunn** [comment]
This PR https://github.com/TAMU-CPT/galaxy-apollo/pull/4 should fix it.

**Comment by nathandunn** [comment]
This is fixed using that PR.
